---
- name: Ensure docker
  hosts: all

  vars:
    docker_users:
      - '{{ ansible_user }}'
    pip_install_packages:
      - name: docker
      - name: docker-compose

  roles:
    - {role: geerlingguy.pip, become: yes}
    - {role: geerlingguy.docker, become: yes}

  tasks:
    - name: reset ssh connection for current docker user
      meta: reset_connection
