---
name: yamllint

on: push

jobs:
  delivery:

    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: Run yamllint
        uses: actionshub/yamllint@main
